/*
 * CUDA kernel code for BM3D
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 * Copyright (c) 2021 WolframRhodium
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

// functions "dct_pack8_interleave4" and "idct_pack8_interleave4"
// are modified from code generated by fftw-3.3.9
// WolframRhodium, 8 May 2021

#include <cfloat>
#include <string>
#include <type_traits>
#include <variant>
#include <vector>

#ifndef __CUDACC__
#define __CUDACC__
#include "cuda_runtime.h"
#endif

#define FMA(a, b, c) (((a) * (b)) + (c))
#define FMS(a, b, c) (((a) * (b)) - (c))
#define FNMS(a, b, c) ((c) - ((a) * (b)))

// CUDA GraphExec for BM3D
cudaGraphExec_t get_graphexec(
    /* shape: [(chroma ? 3 : 1), (2 * radius + 1), 2, height, stride] */
    float * d_res,
    /* shape: [(final_ ? 2 : 1), (chroma ? 3 : 1), (2 * radius + 1), height, stride] */
    float * d_src,
    /* HtoD shape: [(final_ ? 2 : 1), (chroma ? 3 : 1), (2 * radius + 1), height, stride] */
    /* DtoH shape: [(chroma ? 3 : 1), (2 * radius + 1), 2, height, stride] */
    float * h_res,
    int width, int height, int stride,
    float sigma, int block_step, int bm_range,
    int radius, int ps_num, int ps_range,
    bool chroma, float sigma_u, float sigma_v,
    bool final_, float extractor
) noexcept;

std::variant<cudaGraphExec_t, std::string> get_fused_graphexec(
    float * d_res, float * d_src, float * h_res,
    int * d_params, int * h_params,
    int width, int height, int stride,
    float sigma, int block_step, int bm_range,
    int radius, int ps_num, int ps_range,
    bool chroma, float sigma_u, float sigma_v,
    bool final_, float extractor
) noexcept;

std::variant<cudaGraphExec_t, std::string> get_rolling_graphexec(
    float * d_accum, float * d_scratch, float * d_src,
    float * h_src, float * h_output,
    int * d_params, int * h_params,
    int width, int height, int stride,
    const float sigma[3], const int block_step[3],
    const int bm_range[3], const int ps_num[3], const int ps_range[3],
    int radius, int chunk_size, int process_mask, int video_planes,
    int subsampling_w, int subsampling_h,
    bool chroma, bool final_, float extractor
) noexcept;

static constexpr int smem_stride = 32 + 1;

extern "C" __global__ void temporal_normalize(
    float * __restrict__ res,
    int width, int height, int stride,
    int num_planes, int centers
) {
    const int x = blockIdx.x * blockDim.x + threadIdx.x;
    const int y = blockIdx.y;
    const int plane = blockIdx.z;
    if (x >= width || y >= height || plane >= num_planes) {
        return;
    }

    const size_t image_stride = static_cast<size_t>(height) * stride;
    const size_t plane_stride = 2 * image_stride;
    const size_t center_stride = num_planes * plane_stride;
    float weighted_sum = 0.0f;
    float weight = 0.0f;
    for (int center = 0; center < centers; ++center) {
        const size_t offset = center * center_stride + plane * plane_stride + y * stride + x;
        weighted_sum += res[offset];
        weight += res[offset + image_stride];
    }

    res[plane * plane_stride + y * stride + x] = __fdiv_rn(weighted_sum, weight);
}

extern "C" __global__ void rolling_scatter(
    float * __restrict__ accum,
    const float * __restrict__ scratch,
    const int * __restrict__ params,
    int width, int height, int stride,
    int num_planes, int radius, int chunk_size, int center
) {
    const int x = blockIdx.x * blockDim.x + threadIdx.x;
    const int y = blockIdx.y;
    const int plane = blockIdx.z;
    if (x >= width || y >= height || plane >= num_planes) {
        return;
    }

    const int temporal_width = 2 * radius + 1;
    const int source_center = params[1 + center];
    const int first_output = max(0, center - 2 * radius);
    const int last_output = min(chunk_size - 1, center);
    const size_t image_stride = static_cast<size_t>(height) * stride;

    for (int output = first_output; output <= last_output; ++output) {
        const int slice = min(max(
            output + 3 * radius - source_center, 0), temporal_width - 1);
        const size_t scratch_offset =
            (static_cast<size_t>(plane) * temporal_width + slice) *
                2 * image_stride +
            static_cast<size_t>(y) * stride + x;
        const size_t accum_offset =
            (static_cast<size_t>(output) * num_planes + plane) *
                2 * image_stride +
            static_cast<size_t>(y) * stride + x;

        accum[accum_offset] += scratch[scratch_offset];
        accum[accum_offset + image_stride] +=
            scratch[scratch_offset + image_stride];
    }
}

extern "C" __global__ void rolling_normalize(
    float * __restrict__ accum,
    int width, int height, int stride,
    int num_planes, int outputs
) {
    const int x = blockIdx.x * blockDim.x + threadIdx.x;
    const int y = blockIdx.y;
    const int output_plane = blockIdx.z;
    if (x >= width || y >= height || output_plane >= outputs * num_planes) {
        return;
    }

    const size_t image_stride = static_cast<size_t>(height) * stride;
    const size_t offset = static_cast<size_t>(output_plane) *
        2 * image_stride + static_cast<size_t>(y) * stride + x;
    accum[offset] = __fdiv_rn(accum[offset], accum[offset + image_stride]);
}

template <auto transform_impl, int stride=256, int howmany=8, int howmany_stride=32>
__device__
static inline void transform_pack8_interleave4(
    float * __restrict__ data, float * __restrict__ buffer
) {

    #pragma unroll
    for (int iter = 0; iter < howmany; ++iter, data += howmany_stride) {
        float v[8];

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            v[i] = data[i * stride];
        }

        transform_impl(v);

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            data[i * stride] = v[i];
        }
    }
}

// modified from fftw-3.3.9 generated code:
// fftw-3.3.9/rdft/scalar/r2r/e10_8.c and e01_8.c
// (normalized, scaled) DCT-II/DCT-III
template <bool forward>
__device__
static inline void dct(float v[8]) {
    if constexpr (forward) {
        float KP414213562 {+0.414213562373095048801688724209698078569671875};
        float KP1_847759065 {+1.847759065022573512256366378793576573644833252};
        float KP198912367 {+0.198912367379658006911597622644676228597850501};
        float KP1_961570560 {+1.961570560806460898252364472268478073947867462};
        float KP1_414213562 {+1.414213562373095048801688724209698078569671875};
        float KP668178637 {+0.668178637919298919997757686523080761552472251};
        float KP1_662939224 {+1.662939224605090474157576755235811513477121624};
        float KP707106781 {+0.707106781186547524400844362104849039284835938};

        auto T1 = v[0];
        auto T2 = v[7];
        auto T3 = T1 - T2;
        auto Tj = T1 + T2;
        auto Tc = v[4];
        auto Td = v[3];
        auto Te = Tc - Td;
        auto Tk = Tc + Td;
        auto T4 = v[2];
        auto T5 = v[5];
        auto T6 = T4 - T5;
        auto T7 = v[1];
        auto T8 = v[6];
        auto T9 = T7 - T8;
        auto Ta = T6 + T9;
        auto Tn = T7 + T8;
        auto Tf = T6 - T9;
        auto Tm = T4 + T5;
        auto Tb = FNMS(KP707106781, Ta, T3);
        auto Tg = FNMS(KP707106781, Tf, Te);
        v[3] = KP1_662939224 * (FMA(KP668178637, Tg, Tb));
        v[5] = -(KP1_662939224 * (FNMS(KP668178637, Tb, Tg)));
        auto Tp = Tj + Tk;
        auto Tq = Tm + Tn;
        v[4] = KP1_414213562 * (Tp - Tq);
        v[0] = KP1_414213562 * (Tp + Tq);
        auto Th = FMA(KP707106781, Ta, T3);
        auto Ti = FMA(KP707106781, Tf, Te);
        v[1] = KP1_961570560 * (FNMS(KP198912367, Ti, Th));
        v[7] = KP1_961570560 * (FMA(KP198912367, Th, Ti));
        auto Tl = Tj - Tk;
        auto To = Tm - Tn;
        v[2] = KP1_847759065 * (FNMS(KP414213562, To, Tl));
        v[6] = KP1_847759065 * (FMA(KP414213562, Tl, To));
    } else {
        float KP1_662939224 {+1.662939224605090474157576755235811513477121624};
        float KP668178637 {+0.668178637919298919997757686523080761552472251};
        float KP1_961570560 {+1.961570560806460898252364472268478073947867462};
        float KP198912367 {+0.198912367379658006911597622644676228597850501};
        float KP1_847759065 {+1.847759065022573512256366378793576573644833252};
        float KP707106781 {+0.707106781186547524400844362104849039284835938};
        float KP414213562 {+0.414213562373095048801688724209698078569671875};
        float KP1_414213562 {+1.414213562373095048801688724209698078569671875};

        auto T1 = v[0] * KP1_414213562;
        auto T2 = v[4];
        auto T3 = FMA(KP1_414213562, T2, T1);
        auto Tj = FNMS(KP1_414213562, T2, T1);
        auto T4 = v[2];
        auto T5 = v[6];
        auto T6 = FMA(KP414213562, T5, T4);
        auto Tk = FMS(KP414213562, T4, T5);
        auto T8 = v[1];
        auto Td = v[7];
        auto T9 = v[5];
        auto Ta = v[3];
        auto Tb = T9 + Ta;
        auto Te = Ta - T9;
        auto Tc = FMA(KP707106781, Tb, T8);
        auto Tn = FNMS(KP707106781, Te, Td);
        auto Tf = FMA(KP707106781, Te, Td);
        auto Tm = FNMS(KP707106781, Tb, T8);
        auto T7 = FMA(KP1_847759065, T6, T3);
        auto Tg = FMA(KP198912367, Tf, Tc);
        v[7] = FNMS(KP1_961570560, Tg, T7);
        v[0] = FMA(KP1_961570560, Tg, T7);
        auto Tp = FNMS(KP1_847759065, Tk, Tj);
        auto Tq = FMA(KP668178637, Tm, Tn);
        v[5] = FNMS(KP1_662939224, Tq, Tp);
        v[2] = FMA(KP1_662939224, Tq, Tp);
        auto Th = FNMS(KP1_847759065, T6, T3);
        auto Ti = FNMS(KP198912367, Tc, Tf);
        v[3] = FNMS(KP1_961570560, Ti, Th);
        v[4] = FMA(KP1_961570560, Ti, Th);
        auto Tl = FMA(KP1_847759065, Tk, Tj);
        auto To = FNMS(KP668178637, Tn, Tm);
        v[6] = FNMS(KP1_662939224, To, Tl);
        v[1] = FMA(KP1_662939224, To, Tl);
    }
}

// 2-D transposition
// launched by blockDim(x=32, y=1, z=1)
template <int stride=256, int howmany=8, int howmany_stride=32>
__device__
static inline void transpose_pack8_interleave4(
    float * __restrict__ data, float * __restrict__ buffer
) {

    int lane_id;
    asm volatile("mov.u32 %0, %%laneid;" : "=r"(lane_id));

    #pragma unroll
    for (int iter = 0; iter < howmany; ++iter, data += howmany_stride) {
        __syncwarp();

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            buffer[i * smem_stride + lane_id] = data[i * stride];
        }

        __syncwarp();

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            data[i * stride] = buffer[(lane_id % 8) * smem_stride + (lane_id & -8) + i];
        }
    }
}

// launched by blockDim(x=32, y=1, z=1)
template <int stride=32>
__device__
static inline float hard_thresholding(float * data, float sigma) {
    int lane_id;
    asm volatile("mov.u32 %0, %%laneid;" : "=r"(lane_id));

    // number of non-zero coefficients
    #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
    float ks[4] {};
    #else
    float k {};
    #endif

    #pragma unroll
    for (int i = 0; i < 64; ++i) {
        auto val = data[i * stride];

        float thr;
        if (i == 0) {
            thr = (lane_id % 8) ? sigma : 0.0f; // protects DC component
        } else {
            thr = sigma;
        }

        float flag = fabsf(val) >= thr;

        #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
        ks[i % 4] += flag;
        #else
        k += flag;
        #endif
        data[i * stride] = flag ? (val * (1.0f / 4096.0f)) : 0.0f;
    }

    #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
    float k { (ks[0] + ks[1]) + (ks[2] + ks[3]) };
    #endif

    #pragma unroll
    for (int i = 4; i >= 1; i /= 2) {
        k += __shfl_xor_sync(0xFFFFFFFF, k, i, 8);
    }

    return 1.0f / k;
}

// hard thresholding
// launched by blockDim(x=32, y=1, z=1)
__device__
static inline float collaborative_hard(
    float * __restrict__ denoising_patch, float sigma, float * __restrict__ buffer
) {

    constexpr int stride1 = 1;
    constexpr int stride2 = stride1 * 8;

    #pragma unroll
    for (int ndim = 0; ndim < 2; ++ndim) {
        transform_pack8_interleave4<dct<true>, stride1, 8, stride2>(denoising_patch, buffer);
        transpose_pack8_interleave4<stride1, 8, stride2>(denoising_patch, buffer);
    }
    transform_pack8_interleave4<dct<true>, stride2, 8, stride1>(denoising_patch, buffer);

    float adaptive_weight = hard_thresholding<stride1>(denoising_patch, sigma);

    #pragma unroll
    for (int ndim = 0; ndim < 2; ++ndim) {
        transform_pack8_interleave4<dct<false>, stride1, 8, stride2>(denoising_patch, buffer);
        transpose_pack8_interleave4<stride1, 8, stride2>(denoising_patch, buffer);
    }
    transform_pack8_interleave4<dct<false>, stride2, 8, stride1>(denoising_patch, buffer);

    return adaptive_weight;
}

// launched by blockDim(x=32, y=1, z=1)
template <int stride=32>
__device__
static inline float wiener_filtering(
    float * __restrict__ data, float * __restrict__ ref, float sigma
) {
    int lane_id;
    asm volatile("mov.u32 %0, %%laneid;" : "=r"(lane_id));

    // squared l2-norm of coefficients
    #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
    float ks[4] {};
    #else
    float k {};
    #endif

    #pragma unroll
    for (int i = 0; i < 64; ++i) {
        auto val = data[i * stride];
        auto ref_val = ref[i * stride];
        float coeff = (ref_val * ref_val) / (ref_val * ref_val + sigma * sigma);
        if (i == 0) {
            coeff = (lane_id % 8) ? coeff : 1.0f; // protects DC component
        }
        val *= coeff;
        #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
        ks[i % 4] += coeff * coeff;
        #else
        k += coeff * coeff;
        #endif
        data[i * stride] = val * (1.0f / 4096.0f);
    }

    #if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
    float k { (ks[0] + ks[1]) + (ks[2] + ks[3]) };
    #endif

    #pragma unroll
    for (int i = 4; i >= 1; i /= 2) {
        k += __shfl_xor_sync(0xFFFFFFFF, k, i, 8);
    }

    return 1.0f / k;
}

// wiener filtering
// launched by blockDim(x=32, y=1, z=1)
__device__
static inline float collaborative_wiener(
    float * __restrict__ denoising_patch, float * __restrict__ ref_patch,
    float sigma, float * __restrict__ buffer
) {

    constexpr int stride1 = 1;
    constexpr int stride2 = stride1 * 8;

    #pragma unroll
    for (int ndim = 0; ndim < 2; ++ndim) {
        transform_pack8_interleave4<dct<true>, stride1, 8, stride2>(denoising_patch, buffer);
        transpose_pack8_interleave4<stride1, 8, stride2>(denoising_patch, buffer);
    }
    transform_pack8_interleave4<dct<true>, stride2, 8, stride1>(denoising_patch, buffer);

    #pragma unroll
    for (int ndim = 0; ndim < 2; ++ndim) {
        transform_pack8_interleave4<dct<true>, stride1, 8, stride2>(ref_patch, buffer);
        transpose_pack8_interleave4<stride1, 8, stride2>(ref_patch, buffer);
    }
    transform_pack8_interleave4<dct<true>, stride2, 8, stride1>(ref_patch, buffer);

    float adaptive_weight = wiener_filtering<stride1>(denoising_patch, ref_patch, sigma);

    #pragma unroll
    for (int ndim = 0; ndim < 2; ++ndim) {
        transform_pack8_interleave4<dct<false>, stride1, 8, stride2>(denoising_patch, buffer);
        transpose_pack8_interleave4<stride1, 8, stride2>(denoising_patch, buffer);
    }
    transform_pack8_interleave4<dct<false>, stride2, 8, stride1>(denoising_patch, buffer);

    return adaptive_weight;
}

// BM3D kernel
template <
    bool temporal=false, bool chroma=false, bool final_=false,
    bool fused=false, bool rolling=false
>
__global__
#if __CUDA_ARCH__ == 750 || __CUDA_ARCH__ == 860
__launch_bounds__(32, 16)
#elif __CUDA_ARCH__ == 890 || __CUDA_ARCH__ == 1200
__launch_bounds__(32, 24)
#else
__launch_bounds__(32, 32)
#endif
static void bm3d(
    /* shape: [(chroma ? 3 : 1), (2 * radius + 1), 2, height, stride] */
    float * __restrict__ res,
    /* shape: [(final_ ? 2 : 1), (chroma ? 3 : 1), (2 * radius + 1), height, stride] */
    const float * __restrict__ src,
    int width, int height, int stride,
    float sigma, int block_step, int bm_range,
    int _radius, int ps_num, int ps_range,
    [[maybe_unused]] float sigma_u, [[maybe_unused]] float sigma_v,
    float extractor, // used for deteriministic summation
    int source_temporal_width,
    const int * __restrict__ fused_params,
    int graph_center
) {

    __shared__ float buffer[8 * smem_stride];

    int lane_id;
    asm volatile("mov.u32 %0, %%laneid;" : "=r"(lane_id));

    const int sub_lane_id = lane_id % 8; // 0 ~ 7
    int x = (4 * blockIdx.x + lane_id / 8) * block_step;
    int y = block_step * blockIdx.y;
    if (x >= width - 8 + block_step || y >= height - 8 + block_step) {
        return;
    }

    x = min(x, width - 8);
    y = min(y, height - 8);

    int radius = 0;
    if constexpr (temporal) {
        radius = _radius;
    }

    int temporal_stride = height * stride;
    int temporal_width = 2 * radius + 1;
    int source_valid_width = source_temporal_width;
    int source_center = radius;
    int output_z = -1;
    if constexpr (fused) {
        source_valid_width = fused_params[0];
        source_center = fused_params[1 + 2 * graph_center];
        output_z = fused_params[2 + 2 * graph_center];
    } else if constexpr (rolling) {
        source_valid_width = fused_params[0];
        source_center = fused_params[1 + graph_center];
    }
    int source_plane_stride = ((fused || rolling) ?
        source_temporal_width : temporal_width) * temporal_stride;
    int result_plane_stride = (fused ? 1 : temporal_width) * temporal_stride;
    int clip_stride = (chroma ? 3 : 1) * source_plane_stride;

    float current_patch[8];
    const float * const srcpc = &src[source_center * temporal_stride + sub_lane_id];

    {
        const float * srcp = &srcpc[y * stride + x];

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            current_patch[i] = srcp[i * stride];
        }
    }

    #if __CUDA_ARCH__ >= 700
    int membermask =
        ((4 * blockIdx.x * block_step >= bm_range) &&
         ((4 * blockIdx.x + 3) * block_step <= width - 8 - bm_range))
        ? 0xFFFFFFFF
        : 0xFF << (lane_id & -8);
    #endif

    float errors8 = FLT_MAX;
    int index8_x = 0;
    int index8_y = 0;

    {
        int left = max(x - bm_range, 0);
        int right = min(x + bm_range, width - 8);
        int top = max(y - bm_range, 0);
        int bottom = min(y + bm_range, height - 8);

        const float * srcp_row = &srcpc[top * stride + left];
        for (int row_i = top; row_i <= bottom; ++row_i) {
            const float * srcp_col = srcp_row;
            for (int col_i = left; col_i <= right; ++col_i) {
                float errors[2] { 0.0f };

                const float * srcp = srcp_col;

                // promote coherent execution
                #if __CUDA_ARCH__ >= 700
                __syncwarp(membermask);
                #endif

                #pragma unroll
                for (int i = 0; i < 8; ++i) {
                    float val = current_patch[i] - srcp[i * stride];
                    errors[i % 2] += val * val;
                }

                float error = errors[0] + errors[1];

                #if __CUDA_ARCH__ >= 700
                auto active_mask = membermask;
                #else
                auto active_mask = __activemask(); // lock-step execution
                #endif

                error += __shfl_xor_sync(active_mask, error, 1, 8);
                error += __shfl_xor_sync(active_mask, error, 2, 8);
                error += __shfl_xor_sync(active_mask, error, 4, 8);

                auto pre_error = __shfl_up_sync(active_mask, errors8, 1, 8);
                int pre_index_x = __shfl_up_sync(active_mask, index8_x, 1, 8);
                int pre_index_y = __shfl_up_sync(active_mask, index8_y, 1, 8);

                int flag = error < errors8;
                int pre_flag = __shfl_up_sync(active_mask, flag, 1, 8);

                if (flag) {
                    int first = (sub_lane_id == 0) || (!pre_flag);
                    errors8 = first ? error : pre_error;
                    index8_x = first ? col_i : pre_index_x;
                    index8_y = first ? row_i : pre_index_y;
                }

                ++srcp_col;
            }

            srcp_row += stride;
        }
    }
    [[maybe_unused]] int index8_z = radius;

    if /* constexpr */ (temporal) {
        #if __CUDA_ARCH__ >= 700
        membermask = 0xFF << (lane_id & -8); // Only sub-warp convergence is guaranteed
        #endif

        int center_index8_x = index8_x;
        int center_index8_y = index8_y;

        #pragma unroll
        for (int direction = -1; direction <= 1; direction += 2) {
            int last_index8_x = center_index8_x;
            int last_index8_y = center_index8_y;

            for (int t = 1; t <= radius; ++t) {
                /*
                membermask =
                    (((x & -32) >= bm_range + t * ps_range) &&
                     ((x & -32) + bm_range + t * ps_range <= width - 32) &&
                     (y >= bm_range + t * ps_range) &&
                     (y + bm_range + t * ps_range <= height - 8))
                    ? 0xFFFFFFFF
                    : 0xFF << (lane_id & -8);
                */
                int temporal_index = radius + direction * t;
                float frame_errors8 = FLT_MAX;
                int frame_index8_x = 0;
                int frame_index8_y = 0;

                int source_index = temporal_index;
                if constexpr (fused || rolling) {
                    source_index = min(max(
                        source_center - radius + temporal_index, 0),
                        source_valid_width - 1);
                }
                const float * temporal_srcpc = &src[source_index * temporal_stride + sub_lane_id];

                for (int i = 0; i < ps_num; ++i) {
                    int xx = __shfl_sync(0xFFFFFFFF, last_index8_x, i, 8);
                    int yy = __shfl_sync(0xFFFFFFFF, last_index8_y, i, 8);

                    int left = max(xx - ps_range, 0);
                    int right = min(xx + ps_range, width - 8);
                    int top = max(yy - ps_range, 0);
                    int bottom = min(yy + ps_range, height - 8);

                    const float * srcp_row = &temporal_srcpc[top * stride + left];
                    for (int row_i = top; row_i <= bottom; ++row_i) {
                        const float * srcp_col = srcp_row;
                        for (int col_i = left; col_i <= right; ++col_i) {
                            float errors[2] { 0.0f };

                            const float * srcp = srcp_col;

                            // promote coherent execution
                            #if __CUDA_ARCH__ >= 700
                            __syncwarp(membermask);
                            #endif

                            #pragma unroll
                            for (int j = 0; j < 8; ++j) {
                                float val = current_patch[j] - srcp[j * stride];
                                errors[j % 2] += val * val;
                            }

                            float error = errors[0] + errors[1];

                            #if __CUDA_ARCH__ >= 700
                            auto active_mask = membermask;
                            #else
                            auto active_mask = __activemask(); // lock-step execution
                            #endif

                            error += __shfl_xor_sync(active_mask, error, 1, 8);
                            error += __shfl_xor_sync(active_mask, error, 2, 8);
                            error += __shfl_xor_sync(active_mask, error, 4, 8);

                            float pre_error = __shfl_up_sync(
                                active_mask, frame_errors8, 1, 8);
                            int pre_index_x = __shfl_up_sync(
                                active_mask, frame_index8_x, 1, 8);
                            int pre_index_y = __shfl_up_sync(
                                active_mask, frame_index8_y, 1, 8);

                            int flag = error < frame_errors8;
                            int pre_flag = __shfl_up_sync(active_mask, flag, 1, 8);

                            if (flag) {
                                int first = (sub_lane_id == 0) || (!pre_flag);
                                frame_errors8 = first ? error : pre_error;
                                frame_index8_x = first ? col_i : pre_index_x;
                                frame_index8_y = first ? row_i : pre_index_y;
                            }

                            ++srcp_col;
                        }

                        srcp_row += stride;
                    }
                }

                for (int i = 0; i < ps_num; ++i) {
                    float tmp_error = __shfl_sync(0xFFFFFFFF, frame_errors8, i, 8);
                    int tmp_x = __shfl_sync(0xFFFFFFFF, frame_index8_x, i, 8);
                    int tmp_y = __shfl_sync(0xFFFFFFFF, frame_index8_y, i, 8);

                    int flag = tmp_error < errors8;
                    int pre_flag = __shfl_up_sync(0xFFFFFFFF, flag, 1, 8);
                    float pre_error = __shfl_up_sync(0xFFFFFFFF, errors8, 1, 8);
                    int pre_index_x = __shfl_up_sync(0xFFFFFFFF, index8_x, 1, 8);
                    int pre_index_y = __shfl_up_sync(0xFFFFFFFF, index8_y, 1, 8);
                    int pre_index_z = __shfl_up_sync(0xFFFFFFFF, index8_z, 1, 8);

                    if (flag) {
                        int first = (sub_lane_id == 0) || (!pre_flag);
                        errors8 = first ? tmp_error : pre_error;
                        index8_x = first ? tmp_x : pre_index_x;
                        index8_y = first ? tmp_y : pre_index_y;
                        index8_z = first ? temporal_index : pre_index_z;
                    }
                }

                last_index8_x = frame_index8_x;
                last_index8_y = frame_index8_y;
            }
        }
    }

    // insert center block
    {
        auto active_mask = 0xFFFFFFFF;

        int flag;
        if constexpr (temporal) {
            flag = index8_x == x && index8_y == y && index8_z == radius;
        } else {
            flag = index8_x == x && index8_y == y;
        }

        flag += __shfl_xor_sync(active_mask, flag, 1, 8);
        flag += __shfl_xor_sync(active_mask, flag, 2, 8);
        flag += __shfl_xor_sync(active_mask, flag, 4, 8);

        float pre_error = __shfl_up_sync(active_mask, errors8, 1, 8);
        int pre_index_x = __shfl_up_sync(active_mask, index8_x, 1, 8);
        int pre_index_y = __shfl_up_sync(active_mask, index8_y, 1, 8);
        [[maybe_unused]] int pre_index_z;
        if constexpr (temporal) {
            pre_index_z = __shfl_up_sync(active_mask, index8_z, 1, 8);
        }
        if (!flag) {
            int first = (sub_lane_id == 0);
            errors8 = first ? 0.0f : pre_error;
            index8_x = first ? x : pre_index_x;
            index8_y = first ? y : pre_index_y;
            if constexpr (temporal) {
                index8_z = first ? radius : pre_index_z;
            }
        }
    }

    float denoising_patch[64];
    [[maybe_unused]] float ref_patch[64];

    int num_planes = 1;
    if constexpr (chroma) {
        num_planes = 3;
    }
    #pragma unroll
    for (int plane = 0; plane < num_planes; ++plane) {
        if (plane == 1) {
            sigma = sigma_u;
        } else if (plane == 2) {
            sigma = sigma_v;
        }

        if constexpr (chroma) {
            if (sigma < FLT_EPSILON) {
                src += source_plane_stride;
                res += result_plane_stride * 2;
                continue;
            }
        }

        float adaptive_weight;
        if /* constexpr */ (final_) {
            #pragma unroll
            for (int i = 0; i < 8; ++i) {
                int tmp_x = __shfl_sync(0xFFFFFFFF, index8_x, i, 8);
                int tmp_y = __shfl_sync(0xFFFFFFFF, index8_y, i, 8);
                const float * refp;
                if constexpr (temporal) {
                    int tmp_z = __shfl_sync(0xFFFFFFFF, index8_z, i, 8);
                    int source_index = tmp_z;
                    if constexpr (fused || rolling) {
                        source_index = min(max(
                            source_center - radius + tmp_z, 0),
                            source_valid_width - 1);
                    }
                    refp = &src[source_index * temporal_stride + tmp_y * stride + tmp_x + sub_lane_id];
                } else {
                    refp = &src[tmp_y * stride + tmp_x + sub_lane_id];
                }
                const float * srcp = &refp[clip_stride];

                #pragma unroll
                for (int j = 0; j < 8; ++j) {
                    ref_patch[i * 8 + j] = refp[j * stride];
                    denoising_patch[i * 8 + j] = srcp[j * stride];
                }
            }

            adaptive_weight = collaborative_wiener(denoising_patch, ref_patch, sigma, buffer);
        } else {
            #pragma unroll
            for (int i = 0; i < 8; ++i) {
                int tmp_x = __shfl_sync(0xFFFFFFFF, index8_x, i, 8);
                int tmp_y = __shfl_sync(0xFFFFFFFF, index8_y, i, 8);
                const float * srcp;
                if constexpr (temporal) {
                    int tmp_z = __shfl_sync(0xFFFFFFFF, index8_z, i, 8);
                    int source_index = tmp_z;
                    if constexpr (fused || rolling) {
                        source_index = min(max(
                            source_center - radius + tmp_z, 0),
                            source_valid_width - 1);
                    }
                    srcp = &src[source_index * temporal_stride + tmp_y * stride + tmp_x + sub_lane_id];
                } else {
                    srcp = &src[tmp_y * stride + tmp_x + sub_lane_id];
                }

                #pragma unroll
                for (int j = 0; j < 8; ++j) {
                    denoising_patch[i * 8 + j] = srcp[j * stride];
                }
            }

            adaptive_weight = collaborative_hard(denoising_patch, sigma, buffer);
        }

        float * const wdstpc = &res[sub_lane_id];
        float * const weightpc = &res[temporal_stride + sub_lane_id];

        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            int tmp_x = __shfl_sync(0xFFFFFFFF, index8_x, i, 8);
            int tmp_y = __shfl_sync(0xFFFFFFFF, index8_y, i, 8);
            int offset;
            if constexpr (temporal) {
                int tmp_z = __shfl_sync(0xFFFFFFFF, index8_z, i, 8);
                if constexpr (fused) {
                    if (tmp_z != output_z) {
                        continue;
                    }
                    tmp_z = 0;
                }
                offset = tmp_z * 2 * temporal_stride + tmp_y * stride + tmp_x;
            } else {
                offset = tmp_y * stride + tmp_x;
            }

            float * wdstp = &wdstpc[offset];
            float * weightp = &weightpc[offset];

            #pragma unroll
            for (int j = 0; j < 8; ++j) {
                float wdst_val = adaptive_weight * denoising_patch[i * 8 + j];
                float weight_val = adaptive_weight;

                // pre-rounding
                wdst_val = (wdst_val + extractor) - extractor;
                weight_val = (weight_val + extractor) - extractor;

#if defined(__CUDACC_DEVICE_ATOMIC_BUILTINS__) && __CUDA_ARCH__ >= 700
                __nv_atomic_add(&wdstp[j * stride], wdst_val, __NV_ATOMIC_RELAXED, __NV_THREAD_SCOPE_DEVICE);
                __nv_atomic_add(&weightp[j * stride], weight_val, __NV_ATOMIC_RELAXED, __NV_THREAD_SCOPE_DEVICE);
#else // defined(__CUDACC_DEVICE_ATOMIC_BUILTINS__) && __CUDA_ARCH__ >= 700
                atomicAdd(&wdstp[j * stride], wdst_val);
                atomicAdd(&weightp[j * stride], weight_val);
#endif // defined(__CUDACC_DEVICE_ATOMIC_BUILTINS__) && __CUDA_ARCH__ >= 700
            }
        }

        src += source_plane_stride;
        res += result_plane_stride * 2;
    }
}

cudaGraphExec_t get_graphexec(
    float * d_res, float * d_src, float * h_res,
    int width, int height, int stride,
    float sigma, int block_step, int bm_range,
    int radius, int ps_num, int ps_range,
    bool chroma, float sigma_u, float sigma_v, bool final_,
    float extractor
) noexcept {

    size_t pitch { stride * sizeof(float) };
    int temporal_width { 2 * radius + 1 };
    int num_planes { chroma ? 3 : 1 };

    cudaGraph_t graph;
    cudaGraphCreate(&graph, 0);

    cudaGraphNode_t n_HtoD;
    {
        cudaMemcpy3DParms copy_params {};
        int logical_height { (final_ ? 2 : 1) * num_planes * temporal_width * height };
        copy_params.srcPtr = make_cudaPitchedPtr(
            h_res, pitch, width, logical_height);
        copy_params.dstPtr = make_cudaPitchedPtr(
            d_src, pitch, width, logical_height);
        copy_params.extent = make_cudaExtent(
            width * sizeof(float), logical_height, 1);
        copy_params.kind = cudaMemcpyHostToDevice;

        cudaGraphAddMemcpyNode(&n_HtoD, graph, nullptr, 0, &copy_params);
    }

    cudaGraphNode_t n_memset;
    {
        cudaMemsetParams memset_params {};
        memset_params.dst = d_res;
        memset_params.pitch = pitch;
        memset_params.value = 0;
        memset_params.elementSize = 4;
        memset_params.width = width;
        memset_params.height = num_planes * temporal_width * 2 * height;
        cudaGraphAddMemsetNode(&n_memset, graph, nullptr, 0, &memset_params);
    }

    cudaGraphNode_t n_kernel;
    {
        cudaGraphNode_t dependencies[] { n_HtoD, n_memset };
        int source_temporal_width = temporal_width;
        const int * fused_params = nullptr;
        int fused_center = 0;

        void * kernelArgs[] {
            &d_res, &d_src,
            &width, &height, &stride,
            &sigma, &block_step, &bm_range,
            &radius, &ps_num, &ps_range,
            &sigma_u, &sigma_v, &extractor,
            &source_temporal_width, &fused_params, &fused_center
        };

        cudaKernelNodeParams kernel_params {};

        kernel_params.func = reinterpret_cast<void *>(
            radius ? (chroma ? (final_ ? bm3d<true, true, true> : bm3d<true, true, false>)
                             : (final_ ? bm3d<true, false, true> : bm3d<true, false, false>))
                   : (chroma ? (final_ ? bm3d<false, true, true> : bm3d<false, true, false>)
                             : (final_ ? bm3d<false, false, true> : bm3d<false, false, false>))
        );

        kernel_params.gridDim = dim3(
            (width + (4 * block_step - 1)) / (4 * block_step),
            (height + (block_step - 1)) / block_step
        );
        kernel_params.blockDim = dim3(32);
        kernel_params.sharedMemBytes = 0;
        kernel_params.kernelParams = kernelArgs;
        kernel_params.extra = nullptr;

        cudaGraphAddKernelNode(
            &n_kernel, graph,
            dependencies, std::extent_v<decltype(dependencies)>,
            &kernel_params);
    }

    cudaGraphNode_t n_DtoH;
    {
        cudaGraphNode_t dependencies[] { n_kernel };
        cudaMemcpy3DParms copy_params {};
        int logical_height { num_planes * temporal_width * 2 * height };
        copy_params.srcPtr = make_cudaPitchedPtr(
            d_res, pitch, width, logical_height);
        copy_params.dstPtr = make_cudaPitchedPtr(
            h_res, pitch, width, logical_height);
        copy_params.extent = make_cudaExtent(
            width * sizeof(float), logical_height, 1);
        copy_params.kind = cudaMemcpyDeviceToHost;

        cudaGraphAddMemcpyNode(
            &n_DtoH, graph,
            dependencies, std::extent_v<decltype(dependencies)>,
            &copy_params);
    }

    cudaGraphExec_t graphexecp;
    cudaGraphInstantiate(&graphexecp, graph, nullptr, nullptr, 0);

    cudaGraphDestroy(graph);

    return graphexecp;
}

std::variant<cudaGraphExec_t, std::string> get_fused_graphexec(
    float * d_res, float * d_src, float * h_res,
    int * d_params, int * h_params,
    int width, int height, int stride,
    float sigma, int block_step, int bm_range,
    int radius, int ps_num, int ps_range,
    bool chroma, float sigma_u, float sigma_v,
    bool final_, float extractor
) noexcept {
    const auto set_error = [](cudaError_t result, const char * expression) {
        return std::string { "'" } + expression + "' failed: " +
            cudaGetErrorString(result);
    };

    struct GraphGuard {
        cudaGraph_t data {};

        ~GraphGuard() noexcept {
            if (data) {
                cudaGraphDestroy(data);
            }
        }
    } graph;

    const size_t pitch = stride * sizeof(float);
    int centers = 2 * radius + 1;
    int source_temporal_width = 4 * radius + 1;
    int num_planes = chroma ? 3 : 1;
    const size_t source_rows = static_cast<size_t>(final_ ? 2 : 1) *
        num_planes * source_temporal_width * height;

    if (cudaError_t result = cudaGraphCreate(&graph.data, 0); result != cudaSuccess) {
        return set_error(result, "cudaGraphCreate");
    }

    cudaGraphNode_t n_HtoD;
    {
        cudaMemcpy3DParms copy_params {};
        copy_params.srcPtr = make_cudaPitchedPtr(
            h_res, pitch, width, source_rows);
        copy_params.dstPtr = make_cudaPitchedPtr(
            d_src, pitch, width, source_rows);
        copy_params.extent = make_cudaExtent(
            width * sizeof(float), source_rows, 1);
        copy_params.kind = cudaMemcpyHostToDevice;
        if (cudaError_t result = cudaGraphAddMemcpyNode(
            &n_HtoD, graph.data, nullptr, 0, &copy_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddMemcpyNode(HtoD)");
        }
    }

    cudaGraphNode_t n_params;
    if (cudaError_t result = cudaGraphAddMemcpyNode1D(
        &n_params, graph.data, nullptr, 0, d_params, h_params,
        (1 + 2 * static_cast<size_t>(centers)) * sizeof(int),
        cudaMemcpyHostToDevice); result != cudaSuccess) {
        return set_error(result, "cudaGraphAddMemcpyNode1D(params)");
    }

    cudaGraphNode_t n_memset;
    {
        cudaMemsetParams memset_params {};
        memset_params.dst = d_res;
        memset_params.pitch = pitch;
        memset_params.value = 0;
        memset_params.elementSize = 4;
        memset_params.width = width;
        memset_params.height = static_cast<size_t>(centers) * num_planes * 2 * height;
        if (cudaError_t result = cudaGraphAddMemsetNode(
            &n_memset, graph.data, nullptr, 0, &memset_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddMemsetNode");
        }
    }

    std::vector<cudaGraphNode_t> center_nodes(centers);
    for (int center = 0; center < centers; ++center) {
        cudaGraphNode_t dependencies[] { n_HtoD, n_params, n_memset };
        const size_t center_stride = static_cast<size_t>(num_planes) * 2 * height * stride;
        float * center_res = d_res + center * center_stride;
        const int * fused_params = d_params;
        int fused_center = center;

        void * kernel_args[] {
            &center_res, &d_src,
            &width, &height, &stride,
            &sigma, &block_step, &bm_range,
            &radius, &ps_num, &ps_range,
            &sigma_u, &sigma_v, &extractor,
            &source_temporal_width,
            &fused_params, &fused_center
        };

        cudaKernelNodeParams kernel_params {};
        kernel_params.func = reinterpret_cast<void *>(
            chroma ? (final_ ? bm3d<true, true, true, true> : bm3d<true, true, false, true>)
                   : (final_ ? bm3d<true, false, true, true> : bm3d<true, false, false, true>)
        );
        kernel_params.gridDim = dim3(
            (width + (4 * block_step - 1)) / (4 * block_step),
            (height + (block_step - 1)) / block_step);
        kernel_params.blockDim = dim3(32);
        kernel_params.kernelParams = kernel_args;

        if (cudaError_t result = cudaGraphAddKernelNode(
            &center_nodes[center], graph.data,
            dependencies, std::extent_v<decltype(dependencies)>,
            &kernel_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddKernelNode(center)");
        }
    }

    cudaGraphNode_t n_normalize;
    {
        void * kernel_args[] {
            &d_res, &width, &height, &stride,
            &num_planes, &centers
        };
        cudaKernelNodeParams kernel_params {};
        kernel_params.func = reinterpret_cast<void *>(temporal_normalize);
        kernel_params.gridDim = dim3((width + 255) / 256, height, num_planes);
        kernel_params.blockDim = dim3(256);
        kernel_params.kernelParams = kernel_args;
        if (cudaError_t result = cudaGraphAddKernelNode(
            &n_normalize, graph.data,
            center_nodes.data(), center_nodes.size(),
            &kernel_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddKernelNode(normalize)");
        }
    }

    cudaGraphNode_t dependencies[] { n_normalize };
    for (int plane = 0; plane < num_planes; ++plane) {
        const size_t plane_offset = static_cast<size_t>(plane) * 2 * height * pitch;
        cudaMemcpy3DParms copy_params {};
        copy_params.srcPtr = make_cudaPitchedPtr(
            reinterpret_cast<char *>(d_res) + plane_offset,
            pitch, width, 2 * height);
        copy_params.dstPtr = make_cudaPitchedPtr(
            reinterpret_cast<char *>(h_res) + plane_offset,
            pitch, width, 2 * height);
        copy_params.extent = make_cudaExtent(width * sizeof(float), height, 1);
        copy_params.kind = cudaMemcpyDeviceToHost;

        cudaGraphNode_t n_DtoH;
        if (cudaError_t result = cudaGraphAddMemcpyNode(
            &n_DtoH, graph.data,
            dependencies, std::extent_v<decltype(dependencies)>,
            &copy_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddMemcpyNode(DtoH)");
        }
    }

    cudaGraphExec_t graphexec {};
    if (cudaError_t result = cudaGraphInstantiate(
        &graphexec, graph.data, nullptr, nullptr, 0); result != cudaSuccess) {
        return set_error(result, "cudaGraphInstantiate");
    }
    return graphexec;
}

std::variant<cudaGraphExec_t, std::string> get_rolling_graphexec(
    float * d_accum, float * d_scratch, float * d_src,
    float * h_src, float * h_output,
    int * d_params, int * h_params,
    int width, int height, int stride,
    const float sigma[3], const int block_step[3],
    const int bm_range[3], const int ps_num[3], const int ps_range[3],
    int radius, int chunk_size, int process_mask, int video_planes,
    int subsampling_w, int subsampling_h,
    bool chroma, bool final_, float extractor
) noexcept {
    const auto set_error = [](cudaError_t result, const char * expression) {
        return std::string { "'" } + expression + "' failed: " +
            cudaGetErrorString(result);
    };

    struct GraphGuard {
        cudaGraph_t data {};

        ~GraphGuard() noexcept {
            if (data) {
                cudaGraphDestroy(data);
            }
        }
    } graph;

    struct Group {
        int first_plane;
        int planes;
        int width;
        int height;
        size_t source_row;
        size_t accum_row;
    };

    const int temporal_width = 2 * radius + 1;
    const int source_width = chunk_size + 4 * radius;
    const int centers = chunk_size + 2 * radius;
    const int clips = final_ ? 2 : 1;
    const int copy_width = (process_mask & 1) ?
        width : width >> subsampling_w;
    const size_t pitch = static_cast<size_t>(stride) * sizeof(float);

    std::vector<Group> groups;
    size_t source_rows = 0;
    size_t accum_rows = 0;
    if (chroma) {
        groups.push_back(Group {
            .first_plane = 0,
            .planes = 3,
            .width = width,
            .height = height,
            .source_row = 0,
            .accum_row = 0
        });
        source_rows = static_cast<size_t>(clips) * 3 * source_width * height;
        accum_rows = static_cast<size_t>(chunk_size) * 3 * 2 * height;
    } else {
        for (int plane = 0; plane < video_planes; ++plane) {
            if (!(process_mask & (1 << plane))) {
                continue;
            }
            const int plane_width = plane ? width >> subsampling_w : width;
            const int plane_height = plane ? height >> subsampling_h : height;
            groups.push_back(Group {
                .first_plane = plane,
                .planes = 1,
                .width = plane_width,
                .height = plane_height,
                .source_row = source_rows,
                .accum_row = accum_rows
            });
            source_rows += static_cast<size_t>(clips) * source_width * plane_height;
            accum_rows += static_cast<size_t>(chunk_size) * 2 * plane_height;
        }
    }

    if (cudaError_t result = cudaGraphCreate(&graph.data, 0); result != cudaSuccess) {
        return set_error(result, "cudaGraphCreate");
    }

    cudaGraphNode_t source_copy;
    {
        cudaMemcpy3DParms copy_params {};
        copy_params.srcPtr = make_cudaPitchedPtr(
            h_src, pitch, copy_width, source_rows);
        copy_params.dstPtr = make_cudaPitchedPtr(
            d_src, pitch, copy_width, source_rows);
        copy_params.extent = make_cudaExtent(
            static_cast<size_t>(copy_width) * sizeof(float), source_rows, 1);
        copy_params.kind = cudaMemcpyHostToDevice;
        if (cudaError_t result = cudaGraphAddMemcpyNode(
            &source_copy, graph.data, nullptr, 0, &copy_params);
            result != cudaSuccess) {
            return set_error(result, "cudaGraphAddMemcpyNode(source HtoD)");
        }
    }

    cudaGraphNode_t params_copy;
    if (cudaError_t result = cudaGraphAddMemcpyNode1D(
        &params_copy, graph.data, nullptr, 0, d_params, h_params,
        (1 + static_cast<size_t>(centers)) * sizeof(int),
        cudaMemcpyHostToDevice); result != cudaSuccess) {
        return set_error(result, "cudaGraphAddMemcpyNode1D(params)");
    }

    cudaGraphNode_t accum_clear;
    {
        cudaMemsetParams memset_params {};
        memset_params.dst = d_accum;
        memset_params.pitch = pitch;
        memset_params.value = 0;
        memset_params.elementSize = 4;
        memset_params.width = copy_width;
        memset_params.height = accum_rows;
        if (cudaError_t result = cudaGraphAddMemsetNode(
            &accum_clear, graph.data, nullptr, 0, &memset_params);
            result != cudaSuccess) {
            return set_error(result, "cudaGraphAddMemsetNode(accumulators)");
        }
    }

    cudaGraphNode_t previous_group {};
    for (const Group & group : groups) {
        cudaGraphNode_t previous = previous_group;
        for (int center = 0; center < centers; ++center) {
            cudaGraphNode_t scratch_clear;
            cudaGraphNode_t initial_dependencies[] {
                source_copy, params_copy, accum_clear
            };
            const cudaGraphNode_t * dependencies = previous ?
                &previous : initial_dependencies;
            const size_t dependency_count = previous ? 1 :
                std::extent_v<decltype(initial_dependencies)>;

            cudaMemsetParams memset_params {};
            memset_params.dst = d_scratch;
            memset_params.pitch = pitch;
            memset_params.value = 0;
            memset_params.elementSize = 4;
            memset_params.width = group.width;
            memset_params.height = static_cast<size_t>(group.planes) *
                temporal_width * 2 * group.height;
            if (cudaError_t result = cudaGraphAddMemsetNode(
                &scratch_clear, graph.data, dependencies, dependency_count,
                &memset_params); result != cudaSuccess) {
                return set_error(result, "cudaGraphAddMemsetNode(scratch)");
            }

            cudaGraphNode_t center_node;
            float * center_source = d_src + group.source_row * stride;
            const int plane = group.first_plane;
            float center_sigma = sigma[plane];
            float sigma_u = chroma ? sigma[1] : 0.0f;
            float sigma_v = chroma ? sigma[2] : 0.0f;
            int center_block_step = block_step[plane];
            int center_bm_range = bm_range[plane];
            int center_ps_num = ps_num[plane];
            int center_ps_range = ps_range[plane];
            const int * params = d_params;

            void * kernel_args[] {
                &d_scratch, &center_source,
                const_cast<int *>(&group.width),
                const_cast<int *>(&group.height), &stride,
                &center_sigma, &center_block_step, &center_bm_range,
                &radius, &center_ps_num, &center_ps_range,
                &sigma_u, &sigma_v, &extractor,
                const_cast<int *>(&source_width), &params, &center
            };
            cudaKernelNodeParams kernel_params {};
            kernel_params.func = reinterpret_cast<void *>(
                chroma ?
                    (final_ ? bm3d<true, true, true, false, true> :
                              bm3d<true, true, false, false, true>) :
                    (final_ ? bm3d<true, false, true, false, true> :
                              bm3d<true, false, false, false, true>)
            );
            kernel_params.gridDim = dim3(
                (group.width + (4 * center_block_step - 1)) /
                    (4 * center_block_step),
                (group.height + (center_block_step - 1)) /
                    center_block_step);
            kernel_params.blockDim = dim3(32);
            kernel_params.kernelParams = kernel_args;
            if (cudaError_t result = cudaGraphAddKernelNode(
                &center_node, graph.data, &scratch_clear, 1,
                &kernel_params); result != cudaSuccess) {
                return set_error(result, "cudaGraphAddKernelNode(center)");
            }

            cudaGraphNode_t scatter_node;
            float * group_accum = d_accum + group.accum_row * stride;
            void * scatter_args[] {
                &group_accum, &d_scratch, &d_params,
                const_cast<int *>(&group.width),
                const_cast<int *>(&group.height), &stride,
                const_cast<int *>(&group.planes), &radius, &chunk_size, &center
            };
            cudaKernelNodeParams scatter_params {};
            scatter_params.func = reinterpret_cast<void *>(rolling_scatter);
            scatter_params.gridDim = dim3(
                (group.width + 255) / 256, group.height, group.planes);
            scatter_params.blockDim = dim3(256);
            scatter_params.kernelParams = scatter_args;
            if (cudaError_t result = cudaGraphAddKernelNode(
                &scatter_node, graph.data, &center_node, 1,
                &scatter_params); result != cudaSuccess) {
                return set_error(result, "cudaGraphAddKernelNode(scatter)");
            }
            previous = scatter_node;
        }

        cudaGraphNode_t normalize_node;
        float * group_accum = d_accum + group.accum_row * stride;
        void * normalize_args[] {
            &group_accum,
            const_cast<int *>(&group.width),
            const_cast<int *>(&group.height), &stride,
            const_cast<int *>(&group.planes), &chunk_size
        };
        cudaKernelNodeParams normalize_params {};
        normalize_params.func = reinterpret_cast<void *>(rolling_normalize);
        normalize_params.gridDim = dim3(
            (group.width + 255) / 256, group.height,
            chunk_size * group.planes);
        normalize_params.blockDim = dim3(256);
        normalize_params.kernelParams = normalize_args;
        if (cudaError_t result = cudaGraphAddKernelNode(
            &normalize_node, graph.data, &previous, 1,
            &normalize_params); result != cudaSuccess) {
            return set_error(result, "cudaGraphAddKernelNode(normalize)");
        }
        previous_group = normalize_node;

        for (int output = 0; output < chunk_size; ++output) {
            for (int group_plane = 0; group_plane < group.planes; ++group_plane) {
                const int video_plane = group.first_plane + group_plane;
                if (!(process_mask & (1 << video_plane))) {
                    continue;
                }
                const size_t row = group.accum_row +
                    (static_cast<size_t>(output) * group.planes + group_plane) *
                        2 * group.height;
                cudaMemcpy3DParms copy_params {};
                copy_params.srcPtr = make_cudaPitchedPtr(
                    d_accum + row * stride, pitch, group.width, group.height);
                copy_params.dstPtr = make_cudaPitchedPtr(
                    h_output + row * stride, pitch, group.width, group.height);
                copy_params.extent = make_cudaExtent(
                    static_cast<size_t>(group.width) * sizeof(float),
                    group.height, 1);
                copy_params.kind = cudaMemcpyDeviceToHost;
                cudaGraphNode_t output_copy;
                if (cudaError_t result = cudaGraphAddMemcpyNode(
                    &output_copy, graph.data, &normalize_node, 1,
                    &copy_params); result != cudaSuccess) {
                    return set_error(result, "cudaGraphAddMemcpyNode(output DtoH)");
                }
            }
        }
    }

    cudaGraphExec_t graphexec {};
    if (cudaError_t result = cudaGraphInstantiate(
        &graphexec, graph.data, nullptr, nullptr, 0); result != cudaSuccess) {
        return set_error(result, "cudaGraphInstantiate");
    }
    return graphexec;
}
